name: Check Dependabot Alerts

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check_dependabot_alerts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch Dependabot Alerts
        id: fetch_alerts
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          # Fetch Dependabot alerts
          response=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/vulnerability-alerts")

          # Count the number of alerts
          alert_count=$(echo "$response" | jq '. | length')
          
          # Set the alert count as an output
          echo "ALERT_COUNT=$alert_count" >> $GITHUB_ENV

      - name: Notify on Slack
        if: ${{ env.ALERT_COUNT >= 0 }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        run: |
          # Send notification to Slack
          curl -X POST -H 'Content-type: application/json' \
            --data '{"text":"🚨 Dependabot found ${{ env.ALERT_COUNT }} vulnerabilities in your repository!"}' \
            $SLACK_WEBHOOK_URL
